### ISSUE TITLE
Tabs not working

### ISSUE THREAD

**Issue by vaseemsiddiqu** [lorenzoongithub/completely#10]
Tab keys not working...I mean the accesskey, i have a big form designed using this tool.

**Comment by lorenzoongithub** [comment]
@vaseemsiddiqu do you mind giving us more details ? I'd say tab keys do work (obviously not when the popup is visible because they would work just as to help the user finalize the selection). 
In any case, what I would need is a jsfiddle and more detailed explanation on what you think does not work. Thanks very much

**Comment by lorenzoongithub** [comment]
Closing. Not enough information from the user to work out what this is about
